# Generated by Django 2.1.7 on 2020-10-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zhuce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('centigrade', models.CharField(max_length=20)),
                ('ipone', models.IntegerField()),
                ('showtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temperature',
            },
        ),
    ]
