# Generated by Django 2.1.7 on 2020-10-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhuce',
            name='ipone',
            field=models.CharField(max_length=30),
        ),
    ]
